### PR TITLE
Add WSO2 Stream Porcessor and Siddhi

### PR DESCRIPTION
**Pull request by sajithshn**

### CODE REVIEW

**Comment by manuzhang** [comment]
Is WSO2 stream open source ? Could you link to the code base ?

**Comment by sajithshn** [comment]
@manuzhang : Yes, it's open source and components of it are coming from several different repositories. Shall I point to the repository which creates the distirbution ?

**Comment by manuzhang** [comment]
@sajithshn Yeah, that would be better

**Comment by ibiscp** [comment]
Will these be added to the list?

**Comment by manuzhang** [comment]
@ibiscp Added via https://github.com/manuzhang/awesome-streaming/commit/a44a79cfbfaf6ed4de0eca4af11edbd10fd6215c

**Pull request closed without merging**
